# Generated by Django 4.2 on 2023-04-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_set_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='set',
            table='sets',
        ),
    ]
