# Generated by Django 4.2 on 2023-04-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_set_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='set',
            table='set',
        ),
    ]
