# Generated by Django 4.2 on 2023-05-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_prseason'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prseason',
            table='pr_season',
        ),
        migrations.CreateModel(
            name='PRSeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('pr_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prseason')),
            ],
            options={
                'db_table': 'pr_season_results',
                'unique_together': {('player', 'pr_season')},
            },
        ),
    ]
