# Generated by Django 4.2 on 2023-05-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_prseason_hm_remove_prseason_ranks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
    ]
