# Generated by Django 4.2 on 2023-05-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tournament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AddField(
            model_name='tournament',
            name='pr_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.prseason'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region_code',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(null=True),
        ),
    ]
