# Generated by Django 4.2 on 2023-05-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_djangomigrations_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournamentresults',
            options={},
        ),
        migrations.AddField(
            model_name='player',
            name='region_code',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
    ]
