# Generated by Django 4.2 on 2023-05-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_djangomigrations_options_alter_set_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresults',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='set',
            name='player1',
            field=models.ForeignKey(blank=True, db_column='player1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='player2',
            field=models.ForeignKey(blank=True, db_column='player2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sets_player2_set', to='main.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.tournament'),
        ),
    ]
