# Generated by Django 4.2 on 2023-05-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_tournament_region_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
