# Generated by Django 4.2 on 2023-05-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': False},
        ),
    ]
