# Generated by Django 4.2 on 2023-05-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
    ]
