# Generated by Django 4.2 on 2023-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_region_options_alter_tournament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='prseason',
            name='hm',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='prseason',
            name='ranks',
            field=models.JSONField(default=list),
        ),
    ]
