# Generated by Django 4.2 on 2023-05-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_player_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tournamentresults',
            options={},
        ),
    ]
