# Generated by Django 4.2 on 2023-05-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_player_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='region_code',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
        migrations.AddField(
            model_name='tournamentresults',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentresults',
            unique_together={('tour', 'playerid')},
        ),
    ]
