# Generated by Django 4.2 on 2023-05-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tournament_region_code_tournamentresults_playerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playerid',
            new_name='id',
        ),
    ]
