# Generated by Django 4.2 on 2023-05-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_playerid_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prseason',
            name='hm',
        ),
        migrations.RemoveField(
            model_name='prseason',
            name='ranks',
        ),
    ]
