# Generated by Django 4.2 on 2023-05-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_prseason_hm_remove_prseason_ranks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tour_id',
            new_name='id',
        ),
    ]
