# Generated by Django 4.2 on 2023-05-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tournamentresults_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentresults',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentresults',
            name='playerid',
            field=models.ForeignKey(db_column='playerid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentresults',
            name='tour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.tournament'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tournamentresults',
            unique_together={('tour', 'playerid')},
        ),
        migrations.RemoveField(
            model_name='tournamentresults',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tournamentresults',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='tournamentresults',
            name='tournament_id',
        ),
    ]
