# Generated by Django 4.2 on 2023-05-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_tournamentresults_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='player1score',
            new_name='player1_score',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='player2score',
            new_name='player2_score',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='winnerid',
            new_name='winner_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pr_rank',
        ),
    ]
