# Generated by Django 4.2 on 2023-05-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_player1score_set_player1_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresults',
            options={'managed': False},
        ),
    ]
