# Generated by Django 4.2 on 2023-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_tournamentresults_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='tour',
            new_name='tournament_id',
        ),
    ]
