# Generated by Django 4.2 on 2023-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_tournament_id_set_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='pr_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
