# Generated by Django 4.2 on 2023-05-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_set_pr_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='main_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.player'),
        ),
    ]
