# Generated by Django 4.2 on 2023-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_player_main_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='prseason',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
