# Generated by Django 4.2 on 2023-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_set_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pr_notable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
