# Generated by Django 4.2 on 2023-10-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_player_pr_notable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pr_eligible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
