# Generated by Django 4.2 on 2026-01-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_player_pr_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='prseason',
            name='region_code',
            field=models.ForeignKey(blank=True, db_column='region_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='main.region'),
        ),
    ]
