# Generated by Django 4.2 on 2026-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_prseason_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prseason',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prseason',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
