# Generated by Django 5.2.14 on 2026-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_prseason_end_date_alter_prseason_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
