# Generated by Django 5.2.14 on 2026-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_tournament_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sync_error_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
