# Generated by Django 5.2.14 on 2026-05-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_syncerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerrorlog',
            name='tournament_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
