# Generated by Django 5.2.14 on 2026-05-13 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_syncerrorlog_tournament_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='main_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_players', to='main.character'),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_players', to='main.character'),
        ),
    ]
