# Generated by Django 5.2.14 on 2026-05-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_character_player_main_char_player_secondary_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='character_alt',
        ),
        migrations.RemoveField(
            model_name='player',
            name='character_main',
        ),
    ]
