# Generated by Django 5.2.14 on 2026-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_tournament_lat_lng_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
