# Generated by Django 4.2 on 2023-04-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='set',
            table='set',
        ),
    ]
